# Generated by Django 5.0.6 on 2024-07-07 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=20)),
                ('level_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='levels.level')),
            ],
        ),
    ]
