# Generated by Django 5.0.6 on 2024-07-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level_number', models.AutoField(primary_key=True, serialize=False)),
                ('level_description', models.TextField()),
            ],
        ),
    ]
